AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ContentUri:
    Type: String

  Name:
    Type: String

Resources:
  LayerResource:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: !Ref ContentUri

  SSMParameterResource:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref LayerResource
      Name: !Sub /ffxiv-item-name-database/layer/${Name}

Outputs:
  LayerResourceArn:
    Value: !Ref LayerResource

  SSMParameterName:
    Value: !Ref SSMParameterResource
