AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  BeautifulSoup4Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ContentUri: layers/beautifulsoup4
        Name: beautiful-soup-4

  UlidStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ContentUri: layers/ulid
        Name: ulid

Outputs:
  SSMParameterBeautifulSoup4LayerName:
    Value: !GetAttr BeautifulSoup4Stack.Outputs.SSMParameterName
  SSMParameterUlidLayerName:
    Value: !GetAttr UlidStack.Outputs.SSMParameterName
